### ISSUE TITLE
这个解释这么理解？谢谢

### ISSUE THREAD

**Issue by lefex** [banchichen/3DTouch-PeekAndPopGestureDemo#2]
1、判断launchOptions字典内的UIApplicationLaunchOptionsShortcutItemKey是否为空
 2、当不为空时,application:didFinishLaunchWithOptions方法返回NO，否则返回YES

**Comment by banchichen** [comment]
文档里提到的，大概是通过这个key来判断用户是点击了shortcut进来的，还是直接点击图标进来的吧。然后进行不同的处理。
